### ISSUE TITLE
Desh returns "Invalid path" on "ls /"

### ISSUE THREAD

**Issue by Willem3141** [Caster/denvelop#3]
To reproduce:
- Go to a page in English
- Type in the command `ls /` and press Enter

I'd expect `. about whoami` as output, but you get `Desh: Invalid path.`

Also, if you type `ls /` and press Tab, you get this:

![schermafdruk2](https://cloud.githubusercontent.com/assets/7533280/11366423/73392aa2-92ad-11e5-821e-ad5ca658aa97.png)

**Comment by Caster** [comment]
As the commit message says, full site navigation is now possible as well. Hope you like the changes :-)
